#!/usr/bin/env python3
"""The client deliverable: Excel workbook + PDF, hashed and manifested like the footage.

Every number here traces back to the events table; nothing is editable by hand."""

import hashlib
import json
import shutil
import tempfile
import textwrap
import time
from datetime import datetime
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Font
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas as pdfcanvas

import aggregate
import calib

COMPASS = {"N": 0, "E": 90, "S": 180, "W": 270}
# Both taxonomies: the TOR classes and the pre-TOR labels an older fine-tune still emits.
HEAVY = ("heavy_truck", "bus", "large_bus", "hgv_mineral", "hgv_non_mineral")
# The unrefined bucket: a detected goods vehicle nobody has yet split into lgv/mgv/hgv.
# Straddles the heavy boundary, so it blocks the heavy share rather than skewing it.
REVIEW_QUEUE = "goods_vehicle"
METHOD = ("Counts from camera analysis (CountKit); movements paired by tier: "
          "same-camera tracker, cross-camera licence-plate match (evidence, "
          "plates retained internally only), and cross-camera class/transit-time "
          "inference, with calibrated visual re-identification breaking otherwise "
          "ambiguous ties (counted as inference) — the inferred share reported per "
          "cell includes plate-confirmed pairs, so no cell understates uncertainty.")
LICENCE = ("licensed floating-car data — corroboration of survey timing and peaks, "
           "not a second count")
SCHEMATIC = ("arms without compass tags are placed in schematic order "
             "(arm name, clockwise from north) — turns are labelled by that order")
GAPNOTE = "* excludes {n} no-footage bins — see coverage"
PARTNOTE = "* includes hours with partial 15-min coverage — see coverage"
UNPLACED = ("arms beyond the four compass points cannot be turn-labelled — see Movements")
REFINED = ("{n} vehicle classifications refined by human review of evidence crops — "
           "detector originals retained in the raw data annex.")
# Assisted review is disclosed as confirmation, never dressed up as unaided judgment.
REFINED_ASSISTED = ("{n} vehicle classifications refined against evidence crops — "
                    "class proposals generated by a local vision model, each accepted "
                    "or overridden per-crop by the reviewer; detector originals "
                    "retained in the raw data annex.")
MANUAL = ("Movements manually reviewed: {p} paired, {u} unpaired (reviewer overlay) — "
          "counted as observed, actions logged in the raw data annex.")
TURNS = (("left", "Left"), ("straight", "Through"), ("right", "Right"), ("uturn", "U-turn"))


def turn_of(entry_compass, exit_compass):
    """Which of the three arrows a movement belongs to, for left-hand traffic.

    An arm's compass tag says where the arm lies, and a vehicle entering from it is
    already heading the other way — but the tag cancels out of the difference, so the
    approach heading is the ENTRY arm's tag as written (adding 180 to it would shift
    every turn by a half-turn and swap left with right). Clockwise difference:
    90 left, 180 straight, 270 right, 0 U-turn."""
    a, b = COMPASS.get(entry_compass or ""), COMPASS.get(exit_compass or "")
    if a is None or b is None:
        return None
    return {90: "left", 180: "straight", 270: "right", 0: "uturn"}[(b - a) % 360]


def _placed(d):
    """arm -> compass position, and whether any arm had to be placed without a tag.

    Compass tags win; untagged arms fill the free slots clockwise from north. The
    placement is what the diagram draws AND what turns are labelled by, so both read the
    same junction — an arm labelled "(E)" whose turns were classified from a blank tag
    would print three zero arrows beside a name that claims otherwise."""
    tags = {a: (d.get("compass") or {}).get(a, "") for a in d["arms"]}
    placed, free, fallback = {}, ["N", "E", "S", "W"], False
    for a in d["arms"]:
        if tags[a] in free:
            placed[a] = tags[a]
            free.remove(tags[a])
    for a in d["arms"]:
        if a not in placed:
            # No slot of its own: a second arm carrying the same tag, or a fifth arm on a
            # four-point compass. Either way the placement is no longer what was surveyed.
            fallback = True
            if free:
                placed[a] = free.pop(0)
    return placed, fallback


def _hours(d):
    """Bins grouped by local clock hour, in order — the TOR reports 15-minute intervals
    aggregated on an hourly basis."""
    out = {}
    for b in d["bins"]:
        out.setdefault(b["start"][11:13], []).append(b)
    return out


def _inf(n, inf):
    """'inferred' spelled out: a reviewer read '(104 inf)' as infinity — an
    abbreviation that can be mistaken for a number does not belong in a deliverable."""
    return f"{n} ({inf} inferred)" if inf else n


def _turn_cols(unplaced):
    return TURNS + ((("unplaced", "Unplaced"),) if unplaced else ())


def _turn_cells(cells, placed, unplaced=False):
    """The L/T/R/U columns plus a total, for one selection of movement cells.

    A movement whose entry or exit has no compass slot cannot be given a turn, but it
    still happened: it lands in its own bucket and in the total, so a row here never
    reads lower than the same movements do on the Movements sheet."""
    g = {t: [0, 0] for t, _ in _turn_cols(True)}
    for c in cells:
        t = turn_of(placed.get(c["entry"]), placed.get(c["exit"])) or "unplaced"
        g[t][0] += c["count"]
        g[t][1] += c["tier2_count"]
    return ([_inf(*g[t]) for t, _ in _turn_cols(unplaced)]
            + [sum(v[0] for v in g.values())])


def _refined_note(d):
    n = d["qa"].get("refined")
    if not (isinstance(n, (int, float)) and n > 0):
        return None
    return (REFINED_ASSISTED if d["qa"].get("refined_assisted") else REFINED).format(n=n)


def _manual(d):
    """{paired, unpaired} of the reviewer overlay, absent key tolerated: an older
    counts payload predates the overlay and must still export."""
    return {**{"paired": 0, "unpaired": 0}, **(d["qa"]["pairing"].get("manual") or {})}


def _manual_note(d):
    m = _manual(d)
    return MANUAL.format(p=m["paired"], u=m["unpaired"]) if m["paired"] or m["unpaired"] \
        else None


def _bins_in(d, period):
    p = d["peaks"].get(period)
    if not p:
        return []
    i = next((k for k, b in enumerate(d["bins"]) if b["start"] == p["start"]), -1)
    return [b["ts"] for b in d["bins"][i:i + 4]] if i >= 0 else []


def _cells(d, period):
    keep = None if period == "day" else _bins_in(d, period)
    return [c for c in d["movements"]["od"] if keep is None or c["bin"] in keep]


def _phf(d, arm, bins):
    rows = [b for b in d["bins"] if b["ts"] in bins]
    v = [(b["arms"][arm]["total"] if arm else b["total"]) for b in rows]
    return round(sum(v) / (4 * max(v)), 2) if v and max(v) else None


def _total(d, arm=None, bins=None):
    """(entering total, number of no-footage bins it was summed over).

    A gap bin genuinely contributes 0 events, so the sum is right — but the FIGURE is
    not a measured total, and printing it bare contradicts the same sheet's 'no footage'
    cells. Every caller marks the figure from the second number."""
    gaps = 0
    n = 0
    for b in d["bins"]:
        if bins is not None and b["ts"] not in bins:
            continue
        cells = [b["arms"][arm]] if arm else list(b["arms"].values())
        n += sum(c["total"] for c in cells)
        gaps += any(c["gap"] for c in cells)
    return n, gaps


def _mark(v, gaps):
    return f"{v}*" if gaps else v


def _heavy_pct(d):
    """(percent or None, no-footage bins, goods vehicles awaiting review).

    None while goods_vehicle is unrefined: that bucket is unresolved between LGV (not
    heavy) and HGV (heavy), so any percentage computed over it is a guess wearing a
    measurement's clothes. Kalambo's 234 unrefined trucks would report 0.0% heavy —
    a number the reader would take as "no heavy vehicles here". Refuse it instead, for
    the same reason a coverage gap renders 'no footage' and never a zero."""
    tot = heavy = gaps = pending = 0
    for b in d["bins"]:
        gaps += any(c["gap"] for c in b["arms"].values())
        for arm in b["arms"].values():
            for c, n in arm["classes"].items():
                tot += n
                heavy += n if c in HEAVY else 0
                pending += n if c == REVIEW_QUEUE else 0
    if pending:
        return None, gaps, pending
    return (round(heavy / tot * 100, 1) if tot else 0.0), gaps, pending


def _cell(v):
    """Arm and class names are operator input landing in a spreadsheet: openpyxl runs a
    leading =/+/-/@ as a live formula, and refuses control characters outright at save —
    which would kill the whole bundle over one stray character in a calibration."""
    if not isinstance(v, str):
        return v
    s = "".join(ch for ch in v if ch >= " ")
    return "'" + s if s[:1] in "=+-@" else s


# ---------------------------------------------------------------- Excel

def _excel(path, d, config):
    wb = Workbook()
    bold = Font(bold=True)
    arms, classes = d["arms"], d["classes"]
    qa, pr = d["qa"], d["qa"]["pairing"]

    ws = wb.active
    ws.title = "Method"
    rows = [("Site", d["site"]), ("Date", d["date"]),
            ("Company", (config.get("branding") or {}).get("company_name", "")),
            ("Cameras", ", ".join(qa["coverage"]["per_cam"])),
            ("Survey window", " to ".join(qa["coverage"]["window_iso"])),
            ("Coverage hours expected", qa["coverage"]["expected_hours"]),
            ("Pairing rate %", pr["rate"]), ("Same-camera %", pr["same"]),
            ("Cross-camera inferred %", pr["inferred"]),
            ("Inferred share of paired %", pr["inferred_share"]),
            # What the ambiguity gate refused to guess at, and what a human settled.
            ("Ambiguous (gate held)", pr.get("ambiguous", 0)),
            # The evidence tier, split out of the per-cell inferred fold. reads>0 with
            # 0 resolved is a stale sidecar — visible here, not silently absent.
            ("Plate-confirmed pairs",
             (pr.get("plate") or {}).get("pairs", 0)),
            ("Plate reads (resolved to events)",
             f"{(pr.get('plate') or {}).get('reads', 0)} "
             f"({(pr.get('plate') or {}).get('resolved', 0)})"),
            # Visual tie-breaks are inference and counted in the inferred share; the
            # row exists so the reader can see how much of it the embeddings settled.
            ("Visual tie-break pairs (in inferred)",
             (pr.get("emb") or {}).get("pairs", 0)),
            ("QA flags", pr["flagged"]), ("Method", METHOD)]
    if _manual_note(d):
        rows += [("Manually paired", _manual(d)["paired"]),
                 ("Manually unpaired", _manual(d)["unpaired"])]
    # Detected but absent from the vehicle tables — silence here would read as
    # "nothing else was on the footage", which is the one thing it never means.
    for k, n in sorted((qa.get("non_vehicle") or {}).items()):
        rows.append((f"Non-vehicle detections excluded ({k})", n))
    for k, n in sorted((qa.get("unmapped") or {}).items()):
        rows.append((f"Unmapped detector label counted as unmapped ({k})", n))
    for cam, off in qa["offsets"].items():
        rows.append((f"Clock offset {cam} (s)", off))
    for cam, c in qa["coverage"]["per_cam"].items():
        rows.append((f"Recorded hours {cam}", c["hours"]))
        for g in c["gaps_iso"]:
            rows.append((f"Coverage gap {cam}", " to ".join(g)))
    for c in (config.get("classes") or []):
        rows.append((f"Class map {c.get('model')}", c.get("report")))
    for k, v in (config.get("pcu") or {}).items():
        rows.append((f"PCU factor {k}", v))
    if qa["probe"]:
        rows += [("Probe provider", qa["probe"]["provider"]), ("Probe licence", LICENCE)]
    for r in rows:
        ws.append(list(r))
    for c in ws["A"]:
        c.font = bold
    ws.column_dimensions["A"].width = 30
    ws.column_dimensions["B"].width = 90

    ws = wb.create_sheet("Bins")
    head1, head2 = ["Bin"], [""]
    for a in arms:
        head1 += [_cell(a)] + [""] * len(classes)
        head2 += [_cell(c) for c in classes] + ["total"]
    ws.append(head1)
    ws.append(head2)
    for c in ws[1] + ws[2]:
        c.font = bold
    for b in d["bins"]:
        row = [b["start"][11:16]]
        for a in arms:
            cell = b["arms"][a]
            if cell["gap"]:
                # Never 0, never blank: a gap is missing footage, not measured silence.
                row += ["no footage"] * (len(classes) + 1)
            else:
                row += [cell["classes"].get(c, 0) for c in classes] + [cell["total"]]
        ws.append(row)
    marked = False
    for label, period in (("AM peak", "am"), ("PM peak", "pm")):
        bins = _bins_in(d, period)
        if not bins:
            continue
        tot, phf = [label], ["PHF " + label]
        for a in arms:
            n, g = _total(d, a, bins)
            marked |= bool(g)
            tot += [""] * len(classes) + [_mark(n, g)]
            phf += [""] * len(classes) + [_phf(d, a, bins)]
        ws.append(tot)
        ws.append(phf)
    day = ["Day total"]
    for a in arms:
        n, g = _total(d, a)
        marked |= bool(g)
        day += [""] * len(classes) + [_mark(n, g)]
    ws.append(day)
    if marked:
        ws.append([GAPNOTE.format(n=_total(d)[1])])

    ws = wb.create_sheet("Hourly")
    ws.append(["Hour"] + head1[1:] + ["All arms"])
    ws.append(head2 + ["total"])
    for c in ws[1] + ws[2]:
        c.font = bold
    marked = partial = False
    for hh, bs in _hours(d).items():
        bins = [b["ts"] for b in bs]
        # An edge hour the survey only overlaps is a smaller hour, not a quiet one — the
        # same star, so a short first or last row is never read as a measured hourly rate.
        part = len(bs) < 4
        row, rtot, rgap = [f"{hh}:00"], 0, 0
        for a in arms:
            n, g = _total(d, a, bins)
            cls = {}
            for b in bs:
                for k, v in b["arms"][a]["classes"].items():
                    cls[k] = cls.get(k, 0) + v
            # Starred, not "no footage": an hour is a mix of measured and unmeasured
            # quarters, and the sum is real as far as it goes.
            row += [_mark(cls.get(k, 0), g or part) for k in classes] + [_mark(n, g or part)]
            rtot, rgap = rtot + n, rgap + g
        ws.append(row + [_mark(rtot, rgap or part)])
        marked |= bool(rgap)
        partial |= part
    if marked:
        ws.append([GAPNOTE.format(n=_total(d)[1])])
    if partial:
        ws.append([PARTNOTE])

    ws = wb.create_sheet("Movements")
    for label, period in (("AM peak", "am"), ("PM peak", "pm"), ("Full day", "day")):
        if period != "day" and not d["peaks"].get(period):
            # An all-zero matrix reads as "nobody turned", which is a different claim
            # from "this half-day never had a peak hour to report".
            ws.append([f"no {period.upper()} peak recorded"])
            ws.cell(ws.max_row, 1).font = bold
            ws.append([])
            continue
        cells = _cells(d, period)
        ws.append([f"{label} — entry (rows) x exit (cols)"])
        ws.cell(ws.max_row, 1).font = bold
        ws.append(["entry \\ exit"] + [_cell(a) for a in arms])
        grid = {}
        for c in cells:
            g = grid.setdefault((c["entry"], c["exit"]), [0, 0])
            g[0] += c["count"]
            g[1] += c["tier2_count"]
        for en in arms:
            row = [_cell(en)]
            for ex in arms:
                row.append(_inf(*grid.get((en, ex), (0, 0))))
            ws.append(row)
        ws.append([])

    ws = wb.create_sheet("Turns")
    placed, schematic = _placed(d)
    od = d["movements"]["od"]
    # One movement with an unlabellable end is enough to show the column everywhere:
    # a bucket that appears halfway down the sheet reads as a new kind of number.
    unplaced = any(c["entry"] not in placed or c["exit"] not in placed for c in od)
    head = [lbl for _, lbl in _turn_cols(unplaced)] + ["total"]
    ws.append([_cell("Hourly turning volumes — all classes")])
    ws.cell(ws.max_row, 1).font = bold
    ws.append(["Hour", "Entry"] + head)
    for c in ws[ws.max_row]:
        c.font = bold
    marked = partial = False
    for hh, bs in _hours(d).items():
        tss = {b["ts"] for b in bs}
        part = len(bs) < 4
        for a in arms:
            g = any(b["arms"][a]["gap"] for b in bs if a in b["arms"])
            sel = [c for c in od if c["entry"] == a and c["bin"] in tss]
            row = _turn_cells(sel, placed, unplaced)
            row[-1] = _mark(row[-1], g or part)
            ws.append([f"{hh}:00", _cell(a)] + row)
            marked |= g
        partial |= part
    ws.append([])
    for label, period in (("AM peak", "am"), ("PM peak", "pm"), ("Full day", "day")):
        if period != "day" and not d["peaks"].get(period):
            ws.append([_cell(f"no {period.upper()} peak recorded")])
            ws.cell(ws.max_row, 1).font = bold
            ws.append([])
            continue
        cells = _cells(d, period)
        ws.append([_cell(f"{label} — turning volumes by class")])
        ws.cell(ws.max_row, 1).font = bold
        ws.append(["Entry", "Class"] + head)
        for c in ws[ws.max_row]:
            c.font = bold
        for a in arms:
            for cl in classes:
                sel = [c for c in cells if c["entry"] == a and c["cls"] == cl]
                ws.append([_cell(a), _cell(cl)] + _turn_cells(sel, placed, unplaced))
        ws.append([])
    if schematic:
        ws.append([_cell(SCHEMATIC)])
    if any(a not in placed for a in arms):
        ws.append([_cell(UNPLACED)])
    if marked:
        ws.append([GAPNOTE.format(n=_total(d)[1])])
    if partial:
        ws.append([PARTNOTE])

    ws = wb.create_sheet("Summary")
    ws.append(["Metric", "Value"])
    ws.cell(1, 1).font = bold
    ws.cell(1, 2).font = bold
    marked = False
    for label, period in (("AM", "am"), ("PM", "pm")):
        p = d["peaks"].get(period)
        n, g = _total(d, bins=_bins_in(d, period)) if p else (0, 0)
        marked |= bool(g)
        ws.append([f"{label} peak start", p["start"] if p else "none"])
        ws.append([f"{label} peak entering volume", _mark(n, g)])
        ws.append([f"{label} peak PHF", p["phf"] if p else ""])
    n, g = _total(d)
    marked |= bool(g)
    ws.append(["Day total entering", _mark(n, g)])
    hv, hg, hp = _heavy_pct(d)
    marked |= bool(hg)
    ws.append(["% heavy (large bus + HGV)",
               f"pending review of {hp} goods vehicles" if hv is None
               else _mark(hv, hg)])
    for a in arms:
        n, g = _total(d, a)
        marked |= bool(g)
        ws.append([f"Entering {_cell(a)}", _mark(n, g)])
        ws.append([f"AM PHF {_cell(a)}", _phf(d, a, _bins_in(d, "am")) or ""])
    if marked:
        ws.append([GAPNOTE.format(n=_total(d)[1])])
    # Wherever the method is stated, the manual split is stated with it: a refined class
    # is a human overruling the detector, and the client bought the audit trail too.
    for note in (_refined_note(d), _manual_note(d)):
        if note:
            ws.append([_cell(note)])
    wb.save(path)


# ---------------------------------------------------------------- PDF

def _arrow(c, pts):
    """Polyline with a head on the last segment — a turn is one bent arrow, so the
    reader sees where the movement goes without decoding the label."""
    for a, b in zip(pts, pts[1:]):
        c.line(a[0], a[1], b[0], b[1])
    (x0, y0), (x1, y1) = pts[-2], pts[-1]
    n = ((x1 - x0) ** 2 + (y1 - y0) ** 2) ** .5 or 1
    ux, uy = (x1 - x0) / n, (y1 - y0) / n
    px, py = -uy, ux
    c.line(x1, y1, x1 - ux * 5 + px * 2.6, y1 - uy * 5 + py * 2.6)
    c.line(x1, y1, x1 - ux * 5 - px * 2.6, y1 - uy * 5 - py * 2.6)


def _diagram(c, d, x0, y0, size):
    """Plan view, north up, three arrows per approach drawn kerb-first for left-hand
    traffic: the left hook sits nearest the kerb, then straight, then the right hook."""
    cx, cy = x0 + size / 2, y0 + size / 2
    box = size * .18
    c.rect(cx - box, cy - box, box * 2, box * 2)
    c.setFont("Helvetica", 8)
    c.drawString(x0, y0 + size - 6, "N")
    c.line(x0 + 4, y0 + size - 16, x0 + 4, y0 + size - 8)
    c.line(x0 + 4, y0 + size - 8, x0 + 1.5, y0 + size - 12)
    c.line(x0 + 4, y0 + size - 8, x0 + 6.5, y0 + size - 12)

    placed = _placed(d)[0]
    dirs = {"N": (0, 1), "E": (1, 0), "S": (0, -1), "W": (-1, 0)}
    # Hooks stop at the far kerb rather than sailing past it, which is what made the
    # three approaches read as one tangle.
    lane, stop, out = 16, box * .95, box * 1.25 + 22
    # Road edges for every arm position, so the plan reads as a junction rather than
    # as arrows floating around a square.
    for ux, uy in dirs.values():
        px, py = -uy, ux
        for side in (1, -1):
            c.line(cx + ux * box + px * box * side, cy + uy * box + py * box * side,
                   cx + ux * (size / 2) + px * box * side,
                   cy + uy * (size / 2) + py * box * side)
    cells = _cells(d, "am")
    for arm, tag in placed.items():
        ux, uy = dirs[tag]
        # The vehicle drives inward (-u), so +p is its right hand and -p the near kerb.
        px, py = -uy, ux
        turns = {"left": [0, 0], "straight": [0, 0], "right": [0, 0]}
        for cell in cells:
            if cell["entry"] != arm:
                continue
            t = turn_of(tag, placed.get(cell["exit"]))
            if t in turns:                       # U-turns carry no arrow
                turns[t][0] += cell["count"]
                turns[t][1] += cell["count"] if cell["cls"] in HEAVY else 0
        # Kerb-first for left-hand traffic: the left hook runs nearest the kerb, then
        # the straight-ahead lane, then the right hook crossing oncoming traffic.
        for i, t in enumerate(("left", "straight", "right")):
            n, heavy = turns[t]
            off = (i - 1) * lane
            start = (cx + ux * out + px * off, cy + uy * out + py * off)
            if t == "straight":
                pts = [start, (cx - ux * box * .7 + px * off, cy - uy * box * .7 + py * off)]
            else:
                dx, dy = (-px, -py) if t == "left" else (px, py)
                deep = box * .75 if t == "left" else -box * .35
                bend = (cx + ux * deep + px * off, cy + uy * deep + py * off)
                pts = [start, bend, (bend[0] + dx * stop, bend[1] + dy * stop)]
            _arrow(c, pts)
            c.setFont("Helvetica", 6.5)
            # Each count sits at the tail of its own arrow, in lane order across the
            # approach, so the reader never has to guess which arrow a number belongs to.
            c.drawCentredString(cx + ux * (out + 8) + px * off,
                                cy + uy * (out + 8) + py * off - 2,
                                f"{n} ({heavy})" if heavy else str(n))
        c.setFont("Helvetica", 7)
        # Beside the number row, not above it: on an east/west approach a centred name
        # sits at the same height as its own counts and prints over them.
        c.drawCentredString(cx + ux * (out + 9) + px * lane * 2.6,
                            cy + uy * (out + 9) + py * lane * 2.6 - 2,
                            f"{arm[:14]} ({tag})")


def _pdf(path, d, config):
    brand = config.get("branding") or {}
    qa, pr = d["qa"], d["qa"]["pairing"]
    # Uncompressed: the deliverable stays greppable and diffable, so an auditor can
    # pull the text out years later without the tooling we happened to ship with.
    c = pdfcanvas.Canvas(str(path), pagesize=A4, pageCompression=0)
    W, H = A4
    y = H - 20 * mm
    c.setFont("Helvetica-Bold", 13)
    c.drawString(20 * mm, y, f"{brand.get('company_name', 'CountKit')} · {d['site']}"
                             f" · {d['date']}")
    logo = brand.get("logo_path") or ""
    if logo and Path(logo).is_file():
        try:
            c.drawImage(logo, W - 45 * mm, y - 4 * mm, width=25 * mm, height=10 * mm,
                        preserveAspectRatio=True, mask="auto")
        except Exception:
            pass          # a bad logo must never cost the client their report
    y -= 7 * mm
    c.setFont("Helvetica", 8)
    c.drawString(20 * mm, y, "Junction turning-movement survey · counts from camera "
                             "analysis · Africa/Lusaka")

    peak = d["peaks"].get("am")
    if peak:
        _diagram(c, d, 20 * mm, y - 105 * mm, 100 * mm)
    else:
        # A junction drawn with a zero on every arrow is a confident claim; there was
        # simply no AM peak hour to draw.
        c.setFont("Helvetica-Bold", 10)
        c.drawString(20 * mm, y - 55 * mm, "no AM peak recorded")

    bx, by = 130 * mm, y - 30 * mm
    peak_n, peak_g = _total(d, bins=_bins_in(d, "am")) if peak else (0, 0)
    heavy, heavy_g, heavy_p = _heavy_pct(d)
    # An em dash, as the PDF already uses for an absent peak — a headline numeral has no
    # room for the explanation, and the Method sheet carries it.
    heavy_s = "—" if heavy is None else f"{_mark(heavy, heavy_g)}%"
    day_n, day_g = _total(d)
    c.setFont("Helvetica-Bold", 8)
    c.drawString(bx, by, "AM PEAK")
    c.setFont("Helvetica", 8)
    for i, line in enumerate([
            f"interval {peak['start'][11:16] if peak else '—'}",
            f"total entering {_mark(peak_n, peak_g)}",
            f"PHF {peak['phf'] if peak else '—'}",
            f"% heavy {heavy_s}",
            f"pairing {pr['rate']}% ({pr['inferred']}% inferred)",
            "arrows kerb-first (LHT)"]):
        c.drawString(bx, by - 5 * mm - i * 4.4 * mm, line)
    c.rect(bx - 3 * mm, by - 32 * mm, 55 * mm, 38 * mm)

    # Headline numerals: the four figures a reader should get without reading anything.
    hy = by - 46 * mm
    for i, (num, cap) in enumerate([
            (str(_mark(peak_n, peak_g)), "AM PEAK ENTERING"),
            (str(peak["phf"] if peak else "—"), "PHF"),
            (str(_mark(day_n, day_g)), "DAY TOTAL"),
            (heavy_s, "HEAVY")]):
        ry = hy - i * 14 * mm
        c.setFont("Helvetica-Bold", 17)
        c.drawString(bx, ry, num)
        c.setFont("Helvetica", 6)
        c.drawString(bx, ry - 4 * mm, cap)

    ty = y - 118 * mm
    c.setFont("Helvetica-Bold", 9)
    c.drawString(20 * mm, ty, "AM peak movement matrix")
    ty -= 6 * mm
    arms = d["arms"]
    c.setFont("Helvetica", 7)
    if not peak:
        c.drawString(20 * mm, ty, "no AM peak recorded")
    else:
        grid = {}
        for cell in _cells(d, "am"):
            g = grid.setdefault((cell["entry"], cell["exit"]), [0, 0])
            g[0] += cell["count"]
            g[1] += cell["tier2_count"]
        colw = min(28 * mm, (W - 60 * mm) / max(1, len(arms)))
        c.drawString(20 * mm, ty, "entry \\ exit")
        for j, ex in enumerate(arms):
            c.drawString(52 * mm + j * colw, ty, ex[:16])
        for i, en in enumerate(arms):
            ry = ty - (i + 1) * 5 * mm
            c.drawString(20 * mm, ry, en[:18])
            for j, ex in enumerate(arms):
                n, inf = grid.get((en, ex), (0, 0))
                c.drawString(52 * mm + j * colw, ry,
                             f"{n} ({inf} inferred)" if inf else str(n))

    fy = 24 * mm
    c.setFont("Helvetica", 6.5)
    notes = [METHOD] + [n for n in (_refined_note(d), _manual_note(d)) if n]
    if day_g:
        notes.append(GAPNOTE.format(n=day_g))
    if not all((d.get("compass") or {}).get(a) for a in arms):
        notes.append(SCHEMATIC)
    # Largest by duration, not the last one of the day — the longest blind spell is the
    # one a reader has to know about.
    worst = max(((cam, g, iso) for cam, cv in qa["coverage"]["per_cam"].items()
                 for g, iso in zip(cv["gaps"], cv["gaps_iso"])),
                key=lambda x: x[1][1] - x[1][0], default=None)
    if worst:
        mins = round((worst[1][1] - worst[1][0]) / 60)
        notes.append(f"largest coverage gap: {worst[0]} {worst[2][0]} to {worst[2][1]}"
                     f" ({mins} min of no footage)")
    weak = [cam for cam, c in pr["per_cam"].items() if c["rate"] < aggregate.OK_RATE]
    if pr["state"] != "ok" or weak:
        notes.append(f"pairing rate {pr['rate']}% ({pr['inferred_share']}% of pairs "
                     f"inferred) · {pr['flagged']} movements flagged in QA"
                     + (f" · below the {aggregate.OK_RATE}% threshold on "
                        + ", ".join(weak) if weak else ""))
    # Wrapped, never clipped: a method statement cut mid-word reads as a broken report.
    line = 0
    for n in notes:
        for part in textwrap.wrap(n, 150) or [""]:
            c.drawString(20 * mm, fy - line * 3.4 * mm, part)
            line += 1

    if qa["probe"]:
        c.showPage()
        _probe_page(c, d, W, H)
    c.showPage()
    c.save()


def _probe_page(c, d, W, H):
    """Corroboration only — the provider series never merges into a counted one."""
    pr = d["qa"]["probe"]
    y = H - 20 * mm
    c.setFont("Helvetica-Bold", 11)
    c.drawString(20 * mm, y, "Probe corroboration")
    c.setFont("Helvetica", 8)
    c.drawString(20 * mm, y - 6 * mm, "Measured volumes (bars) against provider delay "
                                      "(dashed). Corroboration of timing and peaks only.")
    top = y - 20 * mm
    for arm in d["arms"]:
        # A probe cell carries the display casing when the arm is known and the
        # provider's raw key when it is not — fold both sides before matching.
        cells = {x["bin"]: x for x in pr["cells"]
                 if x["arm"].strip().lower() == arm.strip().lower()}
        vols = [b["arms"][arm]["total"] for b in d["bins"]]
        vmax = max(vols + [1])
        dmax = max([x["delay_s"] for x in cells.values()] + [1])
        c.setFont("Helvetica-Bold", 8)
        c.drawString(20 * mm, top, arm)
        ns = [x["sample_n"] for x in cells.values()]
        c.setFont("Helvetica", 7)
        c.drawString(70 * mm, top, f"median probe sample n={sorted(ns)[len(ns) // 2] if ns else 0}"
                                   f" · {len(ns)} of {len(d['bins'])} bins")
        w = (W - 50 * mm) / max(1, len(d["bins"]))
        for i, b in enumerate(d["bins"]):
            x = 20 * mm + i * w
            c.rect(x, top - 22 * mm, w * .7, vols[i] / vmax * 18 * mm, fill=0)
        c.setDash(3, 2)
        prev = None
        for i, b in enumerate(d["bins"]):
            cell = cells.get(b["ts"])
            if not cell:
                prev = None
                continue          # broken where the provider has no data
            x = 20 * mm + i * w + w * .35
            py = top - 22 * mm + cell["delay_s"] / dmax * 18 * mm
            if prev:
                c.line(prev[0], prev[1], x, py)
            prev = (x, py)
        c.setDash()
        top -= 34 * mm
        if top < 40 * mm:
            break
    c.setFont("Helvetica", 7)
    c.drawString(20 * mm, 22 * mm, f"© {pr['provider']}")
    c.drawString(20 * mm, 18 * mm, LICENCE)


# ---------------------------------------------------------------- bundle

def bundle_dir(data_root, site, date):
    return Path(data_root) / "reports" / site / date


def _sha(p):
    h = hashlib.sha256()
    h.update(p.read_bytes())
    return h.hexdigest()


def build(site, date, data_root, ingest_root, config):
    d = aggregate.counts(site, date, data_root, ingest_root, config)
    # Compass tags live on the calibrations, not in the counts payload.
    d["compass"] = {a["arm"]: a["compass"] for a in calib.arm_map(site)["arms"]}
    if not any(b["total"] for b in d["bins"]):
        raise ValueError(f"{site} {date}: nothing analyzed — run it in Analyze first")
    out = bundle_dir(data_root, site, date)
    out.parent.mkdir(parents=True, exist_ok=True)
    # A unique staging dir per build: on a shared one, a concurrent build's bytes land
    # under this build's manifest, and a hash that vouches for the wrong file is worse
    # than no hash. Only stale dirs get swept — an hour old is a crash, not a rival.
    prefix = out.name + ".tmp-"
    for stale in out.parent.glob(prefix + "*"):
        try:
            if time.time() - stale.stat().st_mtime > 3600:
                shutil.rmtree(stale, ignore_errors=True)
        except OSError:
            pass
    tmp = Path(tempfile.mkdtemp(dir=out.parent, prefix=prefix))
    tmp.chmod(0o755)               # mkdtemp is 0700; the bundle is a deliverable
    stem = f"countkit-{site}-{date}"
    _excel(tmp / f"{stem}.xlsx", d, config)
    _pdf(tmp / f"{stem}.pdf", d, config)
    pr = d["qa"]["pairing"]
    man = {"generated_iso": datetime.now(aggregate.CAT).isoformat(timespec="seconds"),
           "site": site, "date": date,
           "qa": {"pairing_rate": pr["rate"], "inferred_share": pr["inferred_share"],
                  "coverage_hours": d["qa"]["coverage"]["expected_hours"],
                  "flagged": pr["flagged"]},
           "files": {p.name: {"sha256": _sha(p), "bytes": p.stat().st_size}
                     for p in sorted(tmp.iterdir())}}
    (tmp / "manifest.json").write_text(json.dumps(man, indent=2))
    # Same custody discipline as the footage: the bundle appears complete or not at all.
    shutil.rmtree(out, ignore_errors=True)
    tmp.rename(out)
    return {"ok": True, "dir": str(out), **man}


def status(data_root, site, date):
    p = bundle_dir(data_root, site, date) / "manifest.json"
    try:
        return {"exists": True, **json.loads(p.read_text())}
    except (OSError, ValueError):
        return {"exists": False, "files": {}}
